---
abstract: 'Play with Tree and Tree::Persist a la DBIx::Tree'
author:
  - 'Ron Savage <ron@savage.net.au>'
build_requires:
  Test::More: 0.94
  Test::Pod: 1.44
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: artistic
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DBIx-Tree-Persist
provides:
  DBIx::Tree::Persist:
    file: lib/DBIx/Tree/Persist.pm
    version: 1.00
  DBIx::Tree::Persist::Config:
    file: lib/DBIx/Tree/Persist/Config.pm
    version: 1.00
  DBIx::Tree::Persist::Create:
    file: lib/DBIx/Tree/Persist/Create.pm
    version: 1.00
requires:
  Config::Tiny: 2.12
  DBD::SQLite: 1.31
  DBI: 1.612
  DBIx::Admin::CreateTable: 2.07
  File::Slurp: 9999.13
  FindBin::Real: 1.05
  Hash::FieldHash: 0.1
  Tree: 1.01
  Tree::Persist: 1.01
  common::sense: 3.3
resources:
  license: http://www.perlfoundation.org/artistic_license_1_0
version: 1.00
